### ISSUE TITLE
Internal field scannedTypes in endpoint configuration was renamed

### ISSUE THREAD

**Issue by dvdstelt** [NServiceBusExtensions/NServiceBus.HandlerOrdering#79]
## Problem Description

In NServiceBus 7.2 an internal field was renamed. Using Reflection, this package [tries to search](https://github.com/NServiceBusExtensions/NServiceBus.HandlerOrdering/blob/3.0.1/src/HandlerOrdering/OrderHandlers.cs#L28) for `scannedTypes`, which is now called `ScannedTypes`.

NServiceBus 7.1 [code](https://github.com/Particular/NServiceBus/blob/release-7.1/src/NServiceBus.Core/EndpointConfiguration.cs#L285)
NServiceBus 7.2 [code](https://github.com/Particular/NServiceBus/blob/7.2.0/src/NServiceBus.Core/EndpointConfiguration.cs#L128)

**Comment by SimonCropp** [comment]
i am surprised particular is using this library, give how much udi dislikes the handler ordering concept. so what are you using it for?

**Comment by dvdstelt** [comment]
I am not, but someone else is. Instead of directing them to this repo and tell them to open an issue, I did it for them.

**Comment by SimonCropp** [comment]
fair enough. bug given this is a paid product, can you please add a comment with their name so I can ensure they are permitted to use this lib.

**Comment by dvdstelt** [comment]
I'll inform the person who originally asked about this, so that they can choose themselves to do this.

**Comment by SimonCropp** [comment]
@dvdstelt bump

**Comment by SimonCropp** [comment]
closing this one for now. ping me when the new API is added to NSB

**Comment by SimonCropp** [comment]
looking at this change the renamed scannedtypes field is not populated at the time this component tries to read it. https://github.com/Particular/NServiceBus/commit/d33dbecd0f2aff08e2014958755ea10a6aa44c07#diff-f472d9df7895f3c551f095467336887e

So as far as i can tell this is not possibly to be fixed. should i mark this component as deprecated or do you want to do changes to the core to re-enable it. @andreasohlund @timbussmann

**Comment by SimonCropp** [comment]
i looked at this https://github.com/NServiceBusExtensions/NServiceBus.HandlerOrdering/pull/80 and it fails on the sample

**Comment by timbussmann** [comment]
I don't think changing the internal behavior of the `scannedTypes` fields back is really helpful. Would it be useful to be able to to tap into the resolved handlers on the pipeline, e.g. [here](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Pipeline/Incoming/LoadHandlersConnector.cs#L30)  instead?
